In [4]:
# Single neuron
inputs = [1, 2.2, 3.6, 4.9]
weights = [0.5, 0.3, 0.84, 0.4]
bias = 3

output = (
    inputs[0] * weights[0]
    + inputs[1] * weights[1]
    + inputs[2] * weights[2]
    + inputs[3] * weights[3]
    + bias
)
print(output)

9.144


In [5]:
# 3 neurons layer
inputs = [1, 2.2, 3.6, 4.9]
weights1 = [0.5, 0.3, 0.84, 0.4]
weights2 = [0.11, 0.31, 0.84, 0.54]
weights3 = [0.85, 0.23, 0.34, 0.74]
bias1 = 3
bias2 = 1
bias3 = 6

output1 = (
    inputs[0] * weights1[0]
    + inputs[1] * weights1[1]
    + inputs[2] * weights1[2]
    + inputs[3] * weights1[3]
    + bias1
)
output2 = (
    inputs[0] * weights2[0]
    + inputs[1] * weights2[1]
    + inputs[2] * weights2[2]
    + inputs[3] * weights2[3]
    + bias2
)
output3 = (
    inputs[0] * weights3[0]
    + inputs[1] * weights3[1]
    + inputs[2] * weights3[2]
    + inputs[3] * weights3[3]
    + bias3
)

print([output1, output2, output3])

[9.144, 7.462, 12.206]


In [6]:
# Refactoring to 2d matrix - 3 neurons layer
inputs = [1, 2.2, 3.6, 4.9]
weights = [[0.5, 0.3, 0.84, 0.4], [0.11, 0.31, 0.84, 0.54], [0.85, 0.23, 0.34, 0.74]]
bias = [3, 2, 6]

layerOutputs = []  # output of this layer of 3 neurons
for neuronWeights, neuronBias in zip(weights, bias):
    neuronOutput = 0  # output of current neuron
    for input, weight in zip(inputs, neuronWeights):
        neuronOutput += input * weight
    neuronOutput += neuronBias
    layerOutputs.append(neuronOutput)

print(layerOutputs)

[9.144, 8.462, 12.206]


In [73]:
# Shapes

"""
Array 
list: l = [1,2,3]
Shape = (4,)
Type = 1D Array, Vector
---------
listOfList: lol = 
[
    [1,2,3],
    [4,5,6]
]
Shape = (2,4)
Type =  2D Array, Matrix, List of Vectors
---------
listOfListOfList: lolol = 
[
    [
        [1,2,3,3],
        [4,5,6,2]
    ],
    [
        [3,7,8,3],
        [8,6,5,9]
    ],
    [
        [,4,1,3,1],
        [8,9,1,8]
    ]
]
Shape = (3,2,4)
Type = 3D Array
"""
# Tensor is an object that can be represented as an array

'\nArray \nlist: l = [1,2,3]\nShape = (4,)\nType = 1D Array, Vector\n---------\nlistOfList: lol = \n[\n    [1,2,3],\n    [4,5,6]\n]\nShape = (2,4)\nType =  2D Array, Matrix, List of Vectors\n---------\nlistOfListOfList: lolol = \n[\n    [\n        [1,2,3,3],\n        [4,5,6,2]\n    ],\n    [\n        [3,7,8,3],\n        [8,6,5,9]\n    ],\n    [\n        [,4,1,3,1],\n        [8,9,1,8]\n    ]\n]\nShape = (3,2,4)\nType = 3D Array\n'

In [7]:
# Dot Product OR Matrix Product
import numpy as np

# For single neuron
inputs = [1.0, 2.2, 3.6, 4.9]
weights = [0.5, 0.3, 0.84, 0.4]
bias = 3.0

output = np.dot(inputs, weights) + bias

print(output)

# For 3 neurons
inputs = [1, 2.2, 3.6, 4.9]
weights = [[0.5, 0.3, 0.84, 0.4], [0.11, 0.31, 0.84, 0.54], [0.85, 0.23, 0.34, 0.74]]
biases = [3, 2, 6]
# output = np.dot(inputs, weights) + biases <-- This will throw error due shapes not aligned (4,) X (3,4)
output = np.dot(weights, inputs) + biases  # Shapes are aligned (3,4) X (4,)

print(output)

9.144
[ 9.144  8.462 12.206]


In [8]:
# Batches (3 samples of 4 inputs) - this allows to calculate in parallel
inputs = [[1, 2.2, 3.6, 4.9], [5.1, 3.2, 6.6, 8.9], [3.1, 1.2, 8.6, 0.9]]

weights = [[0.5, 0.3, 0.84, 0.4], [0.11, 0.31, 0.84, 0.54], [0.85, 0.23, 0.34, 0.74]]
biases = [3, 2, 6]
# output = np.dot(inputs, weights) + biases -> Shapes are not aligned (3,4) X (3,4)

output = (
    np.dot(inputs, np.array(weights).T) + biases
)  # Shapes are aligned (3,4) X (4,3)
print(output)

[[ 9.144  8.462 12.206]
 [15.614 13.903 19.901]
 [12.494 10.423 12.501]]


In [9]:
# Hidden layers with activiation function
import numpy as np

X = [[1, 2.2, 3.6, 4.9], [5.1, 3.2, 6.6, 8.9], [3.1, 1.2, 8.6, 0.9]]


# Layer
class LayerDense:
    def __init__(self, nInputs, nNeurons):
        self.weights = 0.01 * np.random.randn(nInputs, nNeurons)
        # Here shape of weights (4,3) is opp to previous block (3,4), reason to avoid extra transpose operation for every forward pass
        self.biases = np.zeros((1, nNeurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


# ReLU activation
class ActivationReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


# -----
layer1 = LayerDense(4, 3)
layer2 = LayerDense(3, 2)
activation1 = ActivationReLU()

layer1.forward(X)
print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)

activation1.forward(layer2.output)
print(activation1.output)

[[ 0.06575596 -0.01828519  0.00352017]
 [ 0.09471591 -0.03720227  0.01446798]
 [ 0.12521979 -0.02337999  0.02267963]]
[[0.00048866 0.00016374]
 [0.00066632 0.0003306 ]
 [0.0013075  0.00021344]]
[[0.00048866 0.00016374]
 [0.00066632 0.0003306 ]
 [0.0013075  0.00021344]]


In [10]:
# Hidden layers with activation functions
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()
# Using nnfs spiral sample data of 100 samples of 3 different classes
X, y = spiral_data(100, 3)


# Layer
class LayerDense:
    def __init__(self, nInputs, nNeurons):
        self.weights = 0.01 * np.random.randn(nInputs, nNeurons)
        # Here shape of weights (4,3) is opp to previous block (3,4), reason to avoid extra transpose operation for every forward pass
        self.biases = np.zeros((1, nNeurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


# ReLU activation
class ActivationReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


# -----
layer1 = LayerDense(2, 5)
activation1 = ActivationReLU()

layer1.forward(X)
print(layer1.output[:5])

activation1.forward(layer1.output)
print(activation1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   0.0000000e+00]
 [-8.3581581e-05 -7.9040430e-05 -1.3345221e-04  4.6550449e-05
   4.5684628e-06]
 [-2.3999445e-04  5.9346880e-06 -2.2480826e-04  2.0357311e-05
   6.1002436e-05]
 [-4.1212194e-04  4.3767208e-04 -9.5322714e-05 -1.7302230e-04
   1.9264895e-04]
 [-5.5660505e-04  5.2738853e-04 -1.7207881e-04 -2.0267766e-04
   2.4708614e-04]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 4.6550449e-05 4.5684628e-06]
 [0.0000000e+00 5.9346880e-06 0.0000000e+00 2.0357311e-05 6.1002436e-05]
 [0.0000000e+00 4.3767208e-04 0.0000000e+00 0.0000000e+00 1.9264895e-04]
 [0.0000000e+00 5.2738853e-04 0.0000000e+00 0.0000000e+00 2.4708614e-04]]


In [11]:
# Softmax

# Input -> Exponentiate -> Normalize (Average with diff e^input ) -> Output
# Exponentiate + Normalize = Softmax

import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

# Layer


class LayerDense:
    def __init__(self, nInputs, nNeurons):
        self.weights = 0.01 * np.random.randn(nInputs, nNeurons)
        # Here shape of weights (4,3) is opp to previous block (3,4), reason to avoid extra transpose operation for every forward pass
        self.biases = np.zeros((1, nNeurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


# ReLU activation
class ActivationReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


# Softmax activation
class ActivationSoftmax:
    def forward(self, inputs):
        # axis: 0 -> columns, 1 -> rows
        expValues = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = expValues / np.sum(expValues, axis=1, keepdims=True)
        self.output = probabilities


# -----
# Using nnfs spiral sample data of 100 samples of 3 different classes
X, y = spiral_data(100, 3)
layer1 = LayerDense(2, 3)
activation1 = ActivationReLU()

layer2 = LayerDense(3, 3)
activation2 = ActivationSoftmax()

layer1.forward(X)
activation1.forward(layer1.output)
layer2.forward(activation1.output)
activation2.forward(layer2.output)
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]


In [12]:
# Calculating loss with categorical cross entropy
# -ve sum of the target value multiplied by the log of predicted value for each value in the distribution
import math

softmaxOutput = [0.7, 0.1, 0.2]  # probability / confidence
targetOutput = [1, 0, 0]  # One hot vector

loss = -(
    math.log(softmaxOutput[0]) * targetOutput[0]
    + math.log(softmaxOutput[1]) * targetOutput[1]
    + math.log(softmaxOutput[2]) * targetOutput[2]
)

print(loss)

loss = -math.log(softmaxOutput[0])
print(loss)

0.35667494393873245
0.35667494393873245
