In [1]:
# Single neuron
inputs = [1, 2.2, 3.6, 4.9]
weights = [0.5, 0.3, 0.84, 0.4]
bias = 3

output = (
    inputs[0] * weights[0]
    + inputs[1] * weights[1]
    + inputs[2] * weights[2]
    + inputs[3] * weights[3]
    + bias
)
print(output)

9.144


In [2]:
# 3 neurons layer
inputs = [1, 2.2, 3.6, 4.9]
weights1 = [0.5, 0.3, 0.84, 0.4]
weights2 = [0.11, 0.31, 0.84, 0.54]
weights3 = [0.85, 0.23, 0.34, 0.74]
bias1 = 3
bias2 = 1
bias3 = 6

output1 = (
    inputs[0] * weights1[0]
    + inputs[1] * weights1[1]
    + inputs[2] * weights1[2]
    + inputs[3] * weights1[3]
    + bias1
)
output2 = (
    inputs[0] * weights2[0]
    + inputs[1] * weights2[1]
    + inputs[2] * weights2[2]
    + inputs[3] * weights2[3]
    + bias2
)
output3 = (
    inputs[0] * weights3[0]
    + inputs[1] * weights3[1]
    + inputs[2] * weights3[2]
    + inputs[3] * weights3[3]
    + bias3
)

print([output1, output2, output3])

[9.144, 7.462, 12.206]


In [3]:
# Refactoring to 2d matrix - 3 neurons layer
inputs = [1, 2.2, 3.6, 4.9]
weights = [[0.5, 0.3, 0.84, 0.4], [0.11, 0.31, 0.84, 0.54], [0.85, 0.23, 0.34, 0.74]]
bias = [3, 2, 6]

layerOutputs = []  # output of this layer of 3 neurons
for neuronWeights, neuronBias in zip(weights, bias):
    neuronOutput = 0  # output of current neuron
    for input, weight in zip(inputs, neuronWeights):
        neuronOutput += input * weight
    neuronOutput += neuronBias
    layerOutputs.append(neuronOutput)

print(layerOutputs)

[9.144, 8.462, 12.206]


# Shapes

Array 
list: l = [1,2,3]
Shape = (4,)
Type = 1D Array, Vector
---------
listOfList: lol = 
[
    [1,2,3],
    [4,5,6]
]
Shape = (2,4)
Type =  2D Array, Matrix, List of Vectors
---------
listOfListOfList: lolol = 
[
    [
        [1,2,3,3],
        [4,5,6,2]
    ],
    [
        [3,7,8,3],
        [8,6,5,9]
    ],
    [
        [,4,1,3,1],
        [8,9,1,8]
    ]
]
Shape = (3,2,4)
Type = 3D Array

# Tensor is an object that can be represented as an array

In [5]:
# Dot Product OR Matrix Product
import numpy as np

# For single neuron
inputs = [1.0, 2.2, 3.6, 4.9]
weights = [0.5, 0.3, 0.84, 0.4]
bias = 3.0

output = np.dot(inputs, weights) + bias

print(output)

# For 3 neurons
inputs = [1, 2.2, 3.6, 4.9]
weights = [[0.5, 0.3, 0.84, 0.4], [0.11, 0.31, 0.84, 0.54], [0.85, 0.23, 0.34, 0.74]]
biases = [3, 2, 6]
# output = np.dot(inputs, weights) + biases <-- This will throw error due shapes not aligned (4,) X (3,4)
output = np.dot(weights, inputs) + biases  # Shapes are aligned (3,4) X (4,)

print(output)

9.144
[ 9.144  8.462 12.206]


In [6]:
# Batches (3 samples of 4 inputs) - this allows to calculate in parallel
inputs = [[1, 2.2, 3.6, 4.9], [5.1, 3.2, 6.6, 8.9], [3.1, 1.2, 8.6, 0.9]]

weights = [[0.5, 0.3, 0.84, 0.4], [0.11, 0.31, 0.84, 0.54], [0.85, 0.23, 0.34, 0.74]]
biases = [3, 2, 6]
# output = np.dot(inputs, weights) + biases -> Shapes are not aligned (3,4) X (3,4)

output = (
    np.dot(inputs, np.array(weights).T) + biases
)  # Shapes are aligned (3,4) X (4,3)
print(output)

[[ 9.144  8.462 12.206]
 [15.614 13.903 19.901]
 [12.494 10.423 12.501]]


In [7]:
# Hidden layers with activiation function
import numpy as np

X = [[1, 2.2, 3.6, 4.9], [5.1, 3.2, 6.6, 8.9], [3.1, 1.2, 8.6, 0.9]]


# Layer
class LayerDense:
    def __init__(self, nInputs, nNeurons):
        self.weights = 0.01 * np.random.randn(nInputs, nNeurons)
        # Here shape of weights (4,3) is opp to previous block (3,4), reason to avoid extra transpose operation for every forward pass
        self.biases = np.zeros((1, nNeurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


# ReLU activation
class ActivationReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


# -----
layer1 = LayerDense(4, 3)
layer2 = LayerDense(3, 2)
activation1 = ActivationReLU()

layer1.forward(X)
print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)

activation1.forward(layer2.output)
print(activation1.output)

[[-0.02518929  0.01000133 -0.10602552]
 [-0.07703449  0.04588515 -0.1531715 ]
 [-0.13319932 -0.1075192  -0.02332102]]
[[ 0.00102153  0.00137199]
 [ 0.00228973  0.00258048]
 [ 0.00230288 -0.00159527]]
[[0.00102153 0.00137199]
 [0.00228973 0.00258048]
 [0.00230288 0.        ]]


In [8]:
# Hidden layers with activation functions
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()
# Using nnfs spiral sample data of 100 samples of 3 different classes
X, y = spiral_data(100, 3)


# Layer
class LayerDense:
    def __init__(self, nInputs, nNeurons):
        self.weights = 0.01 * np.random.randn(nInputs, nNeurons)
        # Here shape of weights (4,3) is opp to previous block (3,4), reason to avoid extra transpose operation for every forward pass
        self.biases = np.zeros((1, nNeurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


# ReLU activation
class ActivationReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


# -----
layer1 = LayerDense(2, 5)
activation1 = ActivationReLU()

layer1.forward(X)
print(layer1.output[:5])

activation1.forward(layer1.output)
print(activation1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   0.0000000e+00]
 [-8.3581581e-05 -7.9040430e-05 -1.3345221e-04  4.6550449e-05
   4.5684628e-06]
 [-2.3999445e-04  5.9346880e-06 -2.2480826e-04  2.0357311e-05
   6.1002436e-05]
 [-4.1212194e-04  4.3767208e-04 -9.5322714e-05 -1.7302230e-04
   1.9264895e-04]
 [-5.5660505e-04  5.2738853e-04 -1.7207881e-04 -2.0267766e-04
   2.4708614e-04]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 4.6550449e-05 4.5684628e-06]
 [0.0000000e+00 5.9346880e-06 0.0000000e+00 2.0357311e-05 6.1002436e-05]
 [0.0000000e+00 4.3767208e-04 0.0000000e+00 0.0000000e+00 1.9264895e-04]
 [0.0000000e+00 5.2738853e-04 0.0000000e+00 0.0000000e+00 2.4708614e-04]]


In [9]:
# Softmax

# Input -> Exponentiate -> Normalize (Average with diff e^input ) -> Output
# Exponentiate + Normalize = Softmax

import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

# Layer


class LayerDense:
    def __init__(self, nInputs, nNeurons):
        self.weights = 0.01 * np.random.randn(nInputs, nNeurons)
        # Here shape of weights (4,3) is opp to previous block (3,4), reason to avoid extra transpose operation for every forward pass
        self.biases = np.zeros((1, nNeurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


# ReLU activation
class ActivationReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


# Softmax activation
class ActivationSoftmax:
    def forward(self, inputs):
        # axis: 0 -> columns, 1 -> rows
        expValues = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = expValues / np.sum(expValues, axis=1, keepdims=True)
        self.output = probabilities


# -----
# Using nnfs spiral sample data of 100 samples of 3 different classes
X, y = spiral_data(100, 3)
layer1 = LayerDense(2, 3)
activation1 = ActivationReLU()

layer2 = LayerDense(3, 3)
activation2 = ActivationSoftmax()

layer1.forward(X)
activation1.forward(layer1.output)
layer2.forward(activation1.output)
activation2.forward(layer2.output)
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]


In [10]:
# Calculating loss with categorical cross entropy
# -ve sum of the target value multiplied by the log of predicted value for each value in the distribution
import math

softmaxOutput = [0.7, 0.1, 0.2]  # probability / confidence
targetOutput = [1, 0, 0]  # One hot vector

loss = -(
    math.log(softmaxOutput[0]) * targetOutput[0]
    + math.log(softmaxOutput[1]) * targetOutput[1]
    + math.log(softmaxOutput[2]) * targetOutput[2]
)

print(loss)

loss = -math.log(softmaxOutput[0])
print(loss)

0.35667494393873245
0.35667494393873245


In [25]:
# Implementing Loss

import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

# Layer


class LayerDense:
    def __init__(self, nInputs, nNeurons):
        self.weights = 0.01 * np.random.randn(nInputs, nNeurons)
        # Here shape of weights (4,3) is opp to previous block (3,4), reason to avoid extra transpose operation for every forward pass
        self.biases = np.zeros((1, nNeurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


# ReLU activation
class ActivationReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


# Softmax activation
class ActivationSoftmax:
    def forward(self, inputs):
        # axis: 0 -> columns, 1 -> rows
        expValues = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = expValues / np.sum(expValues, axis=1, keepdims=True)
        self.output = probabilities


# Loss
class Loss:
    def calculate(self, output, y):
        sampleLosses = self.forward(output, y)
        dataLoss = np.mean(sampleLosses)
        return dataLoss


class LossCategoricalCrossEntropy(Loss):
    def forward(self, yPred, yTrue):
        samples = len(yPred)
        yPredClipped = np.clip(yPred, 1e-7, 1 - 1e-7)  # to prevent inf mean
        if len(yTrue.shape) == 1:  # Vector Eg: [0,1,1]
            correctConfidences = yPredClipped[range(samples), yTrue]
        elif (
            len(yTrue.shape) == 2
        ):  # List of one hot encoded values Eg: [[1,0,0],[0,1,0],[0,1,0]]
            correctConfidences = np.sum(yPredClipped * yTrue, axis=1)

        negativeLogLikelihoods = -np.log(correctConfidences)
        return negativeLogLikelihoods


# -----
# Using nnfs spiral sample data of 100 samples of 3 different classes
X, y = spiral_data(100, 3)
layer1 = LayerDense(2, 3)
activation1 = ActivationReLU()

layer2 = LayerDense(3, 3)
activation2 = ActivationSoftmax()

layer1.forward(X)
activation1.forward(layer1.output)
layer2.forward(activation1.output)
activation2.forward(layer2.output)
print(activation2.output[:5])

lossFunction = LossCategoricalCrossEntropy()
loss = lossFunction.calculate(activation2.output, y)
print("Loss:", loss)

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
Loss: 1.0986104


# Derivatives

## Numerical derivatives - D
calculating the slope of the tangent line using two infinitely close points, or as with the code solution — 
calculating the slope of a tangent line made from two points that were "sufficiently close"

This won't be the ideal way as we need to calculate for each weight and bias across neurons in all layers which
is kind of a brute force

The better approach is using analytical derivative with chain rule

Rules:
- Derivative of a constant multiple of the function equals the constant multiple of the function's derivative:
    `D[k*f(x)] = k * D[f(x)]`

- Derivative of a sum/subtraction of functions equals the sum of their derivatives:
    `D[f(x) + g(x)] = D[f(x)] + D[g(x)] , D[f(x) - g(x)] = D[f(x)] - D[g(x)]`

- Derivative of an exponentiation:
    `D[x^n] = n * x^(n-1)`


# Partial Derivatives - d
The partial derivative measures how much impact a single input has on a function’s output.

Rules:
- The partial derivative of the sum with respect to any input equals 1: 
    `f(x,y) = x + y -> dx[f(x,y)] = 1, dy[f(x,y)] = 1`

- The partial derivative of the multiplication operation with 2 inputs, with respect to any input, equals the other input:
    `f(x,y) = x * y -> dx[f(x,y)] = y, dy[f(x,y)] = x`

- The partial derivative of the max function of 2 variables with respect to any of them is 1 if this variable is the biggest and 0 otherwise:
    `f(x,y) = max(x,y) -> dx[f(x,y)] = 1(x>y)`

- The derivative of the max function of a single variable and 0 equals 1 if the variable is greater than 0 and 0 otherwise:
    `f(x) = max(x,0) -> dx[f(x,y)] = 1 (x>0)`

- The derivative of chained functions equals the product of the partial derivatives of the subsequent functions:
    `Dx[f(g(x))] = Dg(x)[f(g(x))] * Dx[g(x)]`

- The same applies to the partial derivatives:
    `dx[f(g(y,h(x,z)))] = dg(y,h(x,z))[f(g(y,h(x,z)))] * d(y,h(x,z))[g(y,h(x,z))] * d(x,z)[h(x,z)]`

- The gradient is a vector of all possible partial derivatives. An example of a triple-input function:
    ```
    G[f(x,y,z)] = [ 
                    dx[f(x,y,z)] 
                    dy[f(x,y,z)] 
                    dz[f(x,y,z)] 
                ] = [
                    dx
                    dy
                    dz
                ] f(x,y,z)
    ```

In [45]:
# Backpropagation for a single neuron

# Forward pass
x = [1.0, -2.0, 3.0]
w = [-3.0, -1.0, 2.0]
b = 1.0

xw0 = x[0] * w[0]
xw1 = x[1] * w[1]
xw2 = x[2] * w[2]

print(xw0, xw1, xw2, b)

z = xw0 + xw1 + xw2 + b
print(z)

# ReLU activation function
y = max(z, 0)
print("Output:", y)

# The first step is to backpropagate our gradients by calculating derivatives and partial derivatives
# with respect to each of our parameters and inputs. To do this, we’re going to use the chain rule.

# Backward pass
# The derivative from the next layer
dvalue = 1.0

# Derivative of ReLU and the chain rule
drelu_dz = dvalue * (1.0 if z > 0 else 0.0)
print(drelu_dz)

# Moving backward through our neural network, next is sum of weighted inputs + bias

# Partial derivatives of the multiplication, the chain rule
dsum_dxw0 = 1
drelu_dxw0 = drelu_dz * dsum_dxw0
print(drelu_dxw0)

dsum_dxw1 = 1
drelu_dxw1 = drelu_dz * dsum_dxw1
print(drelu_dxw1)

dsum_dxw2 = 1
drelu_dxw2 = drelu_dz * dsum_dxw2
print(drelu_dxw2)

dsum_db = 1
drelu_db = drelu_dz * dsum_db
print(drelu_db)

# Partial derivatives of the multiplication, the chain rule
dmul_dx0 = w[0]
dmul_dx1 = w[1]
dmul_dx2 = w[2]
dmul_dw0 = x[0]
dmul_dw1 = x[1]
dmul_dw2 = x[2]

drelu_dx0 = drelu_dxw0 * dmul_dx0
drelu_dw0 = drelu_dxw0 * dmul_dw0
drelu_dx1 = drelu_dxw1 * dmul_dx1
drelu_dw1 = drelu_dxw1 * dmul_dw1
drelu_dx2 = drelu_dxw2 * dmul_dx2
drelu_dw2 = drelu_dxw2 * dmul_dw2

print(drelu_dx0, drelu_dw0, drelu_dx1, drelu_dw1, drelu_dx2, drelu_dw2)

# All together, the partial derivatives above, combined into a vector, make up our gradients.
# Our gradients could be represented as:
dx = [drelu_dx0, drelu_dx1, drelu_dx2]  # gradients on inputs
dw = [drelu_dw0, drelu_dw1, drelu_dw2]  # gradients on weights
db = drelu_db  # gradient on bias...just 1 bias here

print(dx, dw, db)
print(w, b)

# Applying fraction of gradients to minimize
w[0] += -0.001 * dw[0]
w[1] += -0.001 * dw[1]
w[2] += -0.001 * dw[2]
b += -0.001 * db

print(w, b)

# Forward pass with new weights and bias
# Multiplying inputs by weights
xw0 = x[0] * w[0]
xw1 = x[1] * w[1]
xw2 = x[2] * w[2]

# Adding
z = xw0 + xw1 + xw2 + b
# ReLU activation function
y = max(z, 0)
print("Output:", y)  # 5.985

# We’ve successfully decreased this neuron’s output from 6.000 to 5.985. Note that it does not
# make sense to decrease the neuron’s output in a real neural network; we were doing this purely
# as a simpler exercise than the full network.

-3.0 2.0 6.0 1.0
6.0
Output: 6.0
1.0
1.0
1.0
1.0
1.0
-3.0 1.0 -1.0 -2.0 2.0 3.0
[-3.0, -1.0, 2.0] [1.0, -2.0, 3.0] 1.0
[-3.0, -1.0, 2.0] 1.0
[-3.001, -0.998, 1.997] 0.999
Output: 5.985


In [16]:
# Deriving from scratch

import numpy as np

# Passed-in gradient from the next layer
# for the purpose of this example we're going to use
# a vector of 1s
dValues = np.array([[1.0, 1.0, 1.0]])

# We have 3 sets of weights - one set for each neuron
# we have 4 inputs, thus 4 weights
# recall that we keep weights transposed
weights = np.array(
    [[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
).T

# Sum weights related to the given input multiplied by
# the gradient related to the given neuron
# the partial derivative with respect to the input equals the related weight
dX0 = sum(
    [
        weights[0][0] * dValues[0][0],
        weights[0][1] * dValues[0][1],
        weights[0][2] * dValues[0][2],
    ]
)
dX1 = sum(
    [
        weights[1][0] * dValues[0][0],
        weights[1][1] * dValues[0][1],
        weights[1][2] * dValues[0][2],
    ]
)
dX2 = sum(
    [
        weights[2][0] * dValues[0][0],
        weights[2][1] * dValues[0][1],
        weights[2][2] * dValues[0][2],
    ]
)
dX3 = sum(
    [
        weights[3][0] * dValues[0][0],
        weights[3][1] * dValues[0][1],
        weights[3][2] * dValues[0][2],
    ]
)

dInputs = np.array([dX0, dX1, dX2, dX3])
print(dInputs)

# -------------------------------------------------

# As both dValues and weights are numpy arrays, we can simplify the math

# Sum weights related to the given input multiplied by
# the gradient related to the given neuron
dx0 = sum(weights[0] * dValues[0])
dx1 = sum(weights[1] * dValues[0])
dx2 = sum(weights[2] * dValues[0])
dx3 = sum(weights[3] * dValues[0])
dInputs = np.array([dx0, dx1, dx2, dx3])
print(dInputs)

# We can simplify further by direct dot product
dInputs = np.dot(dValues[0], weights.T)
print(dInputs)

# -------------------------------------------------

# Improve to support batch of samples instead of single sample

dValues = np.array([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]])

dInputs = np.dot(dValues, weights.T)
print(dInputs)

# -------------------------------------------------

# To calculate dWeights

# Passed-in gradient from the next layer
# for the purpose of this example we're going to use
# an array of an incremental gradient values
dValues = np.array([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]])

# We have 3 sets of inputs - samples
inputs = np.array([[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2], [-1.5, 2.7, 3.3, -0.8]])

# sum weights of given input
# and multiply by the passed-in gradient for this neuron
dWeights = np.dot(inputs.T, dValues)
print(dWeights)

# -------------------------------------------------

# To calculate dBiases

# One bias for each neuron
# biases are the row vector with a shape (1, neurons)
biases = np.array([[2, 3, 0.5]])

# dBiases - sum values, do this over samples (first axis), keepdims
# since this by default will produce a plain list -
dBiases = np.sum(dValues, axis=0, keepdims=True)
print(dBiases)

# -------------------------------------------------

# To calculate dRelu

# Example layer output
z = np.array([[1, 2, -3, -4], [2, -7, -1, 3], [-1, 2, 5, -1]])

dValues = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# ReLU activation's derivative
dRelu = np.zeros_like(z)
dRelu[z > 0] = 1

print(dRelu)

# Chain rule
dRelu *= dValues
print(dRelu)

# We can improve this as -
# Since the ReLU() derivative array is filled with 1s, which do
# not change the values multiplied by them, and 0s that zero the multiplying value, this means that
# we can take the gradients of the subsequent function and set to 0 all of the values that correspond
# to the ReLU() input and are equal to or less than 0

# ReLU activation's derivative
# with the chain rule applied
dRelu = dValues.copy()
dRelu[z <= 0] = 0
print(dRelu)

[ 0.44 -0.38 -0.07  1.37]
[ 0.44 -0.38 -0.07  1.37]
[ 0.44 -0.38 -0.07  1.37]
[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]
[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]
[[6. 6. 6.]]
[[1 1 0 0]
 [1 0 0 1]
 [0 1 1 0]]
[[ 1  2  0  0]
 [ 5  0  0  8]
 [ 0 10 11  0]]
[[ 1  2  0  0]
 [ 5  0  0  8]
 [ 0 10 11  0]]


In [20]:
# Full code for forward and backward pass of a single neuron with a full layer and batch based partial derivatives

import numpy as np

# Passed-in gradient from the next layer
# for the purpose of this example we're going to use
# an array of an incremental gradient values
dValues = np.array([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]])

# We have 3 sets of inputs - samples
inputs = np.array([[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2], [-1.5, 2.7, 3.3, -0.8]])

# We have 3 sets of weights - one set for each neuron
# we have 4 inputs, thus 4 weights
# recall that we keep weights transposed
weights = np.array(
    [[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
).T

# One bias for each neuron
# biases are the row vector with a shape (1, neurons)
biases = np.array([[2, 3, 0.5]])

# Forward pass
layerOutputs = np.dot(inputs, weights) + biases  # Dense layer
reluOutputs = np.maximum(0, layerOutputs)  # ReLU activation

# Let's optimize and test backpropagation here
# ReLU activation - simulates derivative with respect to input values
# from next layer passed to current layer during backpropagation
dRelu = reluOutputs.copy()
dRelu[layerOutputs <= 0] = 0

# Dense layer
# dInputs - multiply by weights
dInputs = np.dot(dRelu, weights.T)

# dWeights - multiply by inputs
dWeights = np.dot(inputs.T, dRelu)

# dbiases - sum values, do this over samples (first axis), keepdims
# since this by default will produce a plain list
dbiases = np.sum(dRelu, axis=0, keepdims=True)

# Updated parameters
weights += -0.001 * dWeights
biases += -0.001 * dBiases

print(weights)
print(biases)

[[ 0.179515   0.5003665 -0.262746 ]
 [ 0.742093  -0.9152577 -0.2758402]
 [-0.510153   0.2529017  0.1629592]
 [ 0.971328  -0.5021842  0.8636583]]
[[1.994 2.994 0.494]]
